### ISSUE TITLE
rating a video failed!

### ISSUE THREAD

**Issue by benowe1717** [benowe1717/youtube-like-and-download#9]
Running the program through crontab like this:
```2 * * * * /usr/bin/python3 /home/username/youtube-like-and-download-develop/main.py >> ~/errors.log 2>&1```

And looking in the errors.log I see this:
```Traceback (most recent call last):
  File "/home/username/youtube-like-and-download-develop/main.py", line 108, in <module>
    main()
  File "/home/username/youtube-like-and-download-develop/main.py", line 101, in main
    ytDL.rateVideos()
TypeError: rateVideos() missing 1 required positional argument: 'access_token'```

**Comment by benowe1717** [comment]
While testing a fix for this, I ran in to this error:
```Traceback (most recent call last):
  File "main.py", line 220, in <module>
    main()
  File "main.py", line 213, in main
    ytDL.rateVideos(yto._access_token)
  File "/home/benjamin/new_work/youtubeDL.py", line 250, in rateVideos
    json_data = json.loads(r.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

Fixing this in the same branch

**Comment by benowe1717** [comment]
This is now fixed in: https://github.com/benowe1717/youtube-like-and-download/pull/11 and has been merged into develop
